language: php

php:
  - 5.6
  - 7

services:
  - mysql

before_script:
  - mysql -e 'create database symfony;'
  - composer install
  - php app/console doctrine:database:create
  - php app/console doctrine:schema:create

script: phpunit --coverage-text
